spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rboot?charset=utf8mb4&serverTimezone=UTC
    username: atx
    password: d2luZ294JEA=
    tomcat:
      max-active: 20
      validation-query: select 1
      initial-size: 10

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
