spring:
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  data:
    mongodb:

      uri: mongodb://127.0.0.1:27017

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/rboot?charset=utf8mb4&serverTimezone=UTC
    username: atx
    password: d2luZ294JEA=
    tomcat:
      max-active: 20
      validation-query: select 1
      initial-size: 10

user:
  name: black